/*
 * generated by Xtext
 */
package net.sourceforge.ufoai.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 */
public class UFOScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
