/*
 * generated by Xtext
 */
package net.sourceforge.ufoai.ui.outline;

import net.sourceforge.ufoai.ufoScript.UFONode;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 */
public class UFOScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {

	protected boolean _isLeaf(UFONode node) {
		// filter all terminal values
		return node.getNodes().isEmpty();
	}
}
