/*
 * generated by Xtext
 */
package net.sourceforge.ufoai.ui;

import net.sourceforge.ufoai.ui.properties.UFOScriptPropertyViewer;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.contentassist.XtextContentAssistProcessor;

import com.google.inject.Binder;
import com.google.inject.name.Named;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UFOScriptUiModule extends net.sourceforge.ufoai.ui.AbstractUFOScriptUiModule {
	public UFOScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		Named named = com.google.inject.name.Names.named(XtextContentAssistProcessor.COMPLETION_AUTO_ACTIVATION_CHARS);
		binder.bind(String.class).annotatedWith(named).toInstance(".,:");
	}

	public Class<? extends XtextEditor> bindEditor() {
		return UFOScriptPropertyViewer.class;
	}
}
