#! /bin/bash

DIR="${1:-.}"
echo "using directory $DIR"

EXT="ac am c h cpp m pl po py qe4 rc sh tex txt ufo ump py map"
# define REPORTNEGATIVES to report all files that had no modifications performed
#REPORTNEGATIVES=yes

# define REPORTPOSITIVES to report action on svn setting
#REPORTPOSITIVES=yes

echo "setting eol style to native"
set -f
for i in $EXT; do
    [[ $NOTFIRST ]] && {
	EXPRESSION="$EXPRESSION -o"
    } || {
	NOTFIRST=yes
    }
    EXPRESSION="$EXPRESSION -name *.$i"
done

while read FILENAME; do
    if [ "$(svn pg svn:eol-style "$FILENAME")" == "native" ]; then
	[[ $REPORTNEGATIVES ]] && echo "not setting eol style for $FILENAME, already native"
    else
	# make sure there are no dos style newlines before setting eol style - that can fail if there are mixed newlines
	sed -i 's/\r//' $FILENAME
	[[ $REPORTPOSITIVES ]] && echo "*** setting svn:eol-style native for $FILENAME"
	svn ps svn:eol-style native "$FILENAME"
    fi
done < <(find "$DIR" -type f ! -wholename '*/.svn*' $EXPRESSION)
set +f

echo "setting mime types"
mime () {
    while read FILENAME; do
    	if [ "$(svn pg svn:mime-type $FILENAME)" == "$2" ]; then
	    [[ $REPORTNEGATIVES ]] && echo "not setting mime type for $FILENAME, already $2"
	else
	    [[ $REPORTPOSITIVES ]] && echo "*** setting svn:mime-type to $2 for $FILENAME"
	    svn ps svn:mime-type $2 $FILENAME
	fi
    done < <(find "$DIR" -name "*.$1")
}

mime bmp image/bmp
mime jpg image/jpeg
mime ogg application/ogg
mime blend application/x-blender
mime exe application/x-executable
mime png image/png
mime tga image/x-tga
mime wav audio/x-wav
mime xcf image/x-xcf
mime xbm image/x-xbitmap
mime xpm image/x-xpixmap
mime 3ds application/x-3ds
mime psd image/psd
mime dll application/octet-stream
mime pdf application/pdf
mime doc application/msword
mime zip application/zip
mime ico image/x-icon
