#! /bin/sh

DIR=.

if [ $# -eq 1 ]
then
    echo "Use $1"
    DIR="$1"
fi

EXT="ac am c h cpp m pl po py qe4 rc sh tex txt ufo ump py"

for i in $EXT; do
        find "$DIR" -name "*.$i" -exec ./eol {} \;
done

find "$DIR" -name ".cvsignore" -exec svn rm {} \;

mime () {
        find "$DIR" -name "*.$1" -exec svn ps svn:mime-type $2 {} \;
}

mime 3ds   application/x-3ds
mime blend application/x-blender
mime bmp   image/bmp
mime dll   application/x-msdownload
mime doc   application/msword
mime exe   application/x-executable
mime ico   image/x-icon
mime jpg   image/jpeg
mime ogg   application/ogg
mime pdf   application/pdf
mime png   image/png
mime psd   image/psd
mime tga   image/x-tga
mime wav   audio/x-wav
mime xbm   image/x-xbitmap
mime xcf   image/x-xcf
mime xpm   image/x-xpixmap
mime zip   application/zip
