MAPSDIR = .

MAPSRCS = $(shell dir /S/B $(MAPSDIR)\*.map) # Windows version. TODO still needs the "tutorial*" and "prefab*" excluded.
BSPS = $(MAPSRCS:.map=.bsp)

QRAD3FLAGS = -bounce 0 -chop 32 -extra

all: $(BSPS)

$(BSPS): %.bsp: %.map
	ufo2map $(QRAD3FLAGS) $<
