/*
 * generated by Xtext
 */
package net.sourceforge.ufoai.ui.contentassist;

import net.sourceforge.ufoai.ui.contentassist.AbstractUFOScriptProposalProvider;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class UFOScriptProposalProvider extends
		AbstractUFOScriptProposalProvider {
}
