#define SAVE_MESSAGEOPTIONS_MESSAGEOPTIONS "messageOptions"
#define SAVE_MESSAGEOPTIONS_TYPE "type"
#define SAVE_MESSAGEOPTIONS_NAME "name"
#define SAVE_MESSAGEOPTIONS_NOTIFY "notify"
#define SAVE_MESSAGEOPTIONS_PAUSE "pause"
#define SAVE_MESSAGEOPTIONS_SOUND "sound"

