#define SAVE_PRODUCE_PRODUCTION "production"
#define SAVE_PRODUCE_QUEUE "queue"
#define SAVE_PRODUCE_NUMITEMS "numItems"
#define SAVE_PRODUCE_ITEM "item"
#define SAVE_PRODUCE_ITEMID "itemid"
#define SAVE_PRODUCE_AIRCRAFTID "aircraftid"
#define SAVE_PRODUCE_UFOIDX "UFOIDX"
#define SAVE_PRODUCE_AMOUNT "amount"
#define SAVE_PRODUCE_PERCENTDONE "percentDone"
#define SAVE_PRODUCE_ITEMS_CACHED "itemsCached"

