#define SAVE_INVENTORY_INVENTORY "inventory"
#define SAVE_INVENTORY_ITEM "item"
#define SAVE_INVENTORY_AMMO "ammo"
#define SAVE_INVENTORY_ROTATED "rotated"
#define SAVE_INVENTORY_AMOUNT "amount"
#define SAVE_INVENTORY_X "x"
#define SAVE_INVENTORY_Y "y"
#define SAVE_INVENTORY_CONTAINER "container"
#define SAVE_INVENTORY_WEAPONID "weaponid"
#define SAVE_INVENTORY_MUNITIONID "munitionid"

