#define SAVE_ALIENBASE_ALIENBASES "alienBases"
#define SAVE_ALIENBASE_NUM "num"
#define SAVE_ALIENBASE_BASE "base"
#define SAVE_ALIENBASE_POS "pos"
#define SAVE_ALIENBASE_SUPPLY "supply"
#define SAVE_ALIENBASE_STEALTH "stealth"
