#define SAVE_UFORECOVERY_STOREDUFOS "storedUFOs"
#define SAVE_UFORECOVERY_UFO "UFO"
#define SAVE_UFORECOVERY_UFOID "id"
#define SAVE_UFORECOVERY_DAY "day"
#define SAVE_UFORECOVERY_SEC "sec"
#define SAVE_UFORECOVERY_STATUS "status"
#define SAVE_UFORECOVERY_CONDITION "condition"
#define SAVE_UFORECOVERY_INSTALLATIONIDX "installationIDX"

