#define SAVE_NATION_NATIONS "nations"
#define SAVE_NATION_NATION "nation"
#define SAVE_NATION_MONTH "month"
#define SAVE_NATION_INUSE "inuse"
#define SAVE_NATION_HAPPINESS "happiness"
#define SAVE_NATION_XVI "xvi"
#define SAVE_NATION_ALIENFRIENDLY "alienfriendly"
