#!/usr/bin/python

#
# @brief extract wiki documentation about behaviour from .h and .c files
# @license Public domain
# @return a MediaWiki document into stdout (http://ufoai.ninex.info/wiki/index.php/UI_node_behaviours)
# @todo generate confunc too
#

import os, os.path, sys
from ExtractNodeBehaviour import *

def genPropertyDoc(element):
	result = ""
	
	for d in element.doc:
		if d.startswith("@todo"):
			result += '<div style="border:2px solid red;padding:2px;">' + d + '</div> '
		elif d.startswith("@"):
			result += '<div style="border:2px solid green;padding:2px;">' + d + '</div> '
		else:
			result += d + ' '
	return result

def genBehaviourDoc(node):
	result = ""
	label = ""

	result += '== ' + node.name + ' ==\n'
	if node.extends != None:
		result += ':This node inherite [[#' + node.extends + ']]. Check this node for more properties.\n'

	if node.doc != "":
		result += node.doc + '\n'

	if len(node.properties) + len(node.methods) + len(node.confuncs) != 0:
		result += '\n'
		result += '{| border="1" cellpadding="5" cellspacing="0"\n'
		result += '! Name !! Type !! Description\n'
		
		list = node.properties.keys()
		list.sort()
		for name in list:
			e = node.properties[name]
			result += '|-\n'
			result += '| ' + e.name + ' || [[' + e.type + ']] || ' + genPropertyDoc(e) + '\n'
			pass
		list = node.methods.keys()
		list.sort()
		for name in list:
			e = node.methods[name]
			result += '|-\n'
			result += '| ' + e.name + ' || [[' + e.type + ']] || ' + genPropertyDoc(e) + '\n'
			pass
		list = node.confuncs.keys()
		list.sort()
		for name in list:
			e = node.confuncs[name]
			result += '|-\n'
			result += '| ' + e.name + ' || [[' + e.type + ']] || ' + genPropertyDoc(e) + '\n'
			pass
		result += '|}\n'

	return result

def genDoc(nodeList):
	list = nodeList.keys()
	list.sort()
	print "This page is '''autogenerated'''. Please do not edit it. Use the [[Talk:UI node behaviours|talk page]] of update the source code."
	print
	for name in list:
		print genBehaviourDoc(nodeList[name])
	print
	print '[[Category:GUIs]]'

extract = ExtractNodeBehaviour()
behaviours = extract.getBehaviours()
genDoc(behaviours)
