/*
 * generated by Xtext
 */
package net.sourceforge.ufoai;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class UFOScriptRuntimeModule extends net.sourceforge.ufoai.AbstractUFOScriptRuntimeModule {

}
