/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_campaign_editor (void);
GtkWidget* create_mission_dialog (void);

GtkWidget *mis_txt;
GtkWidget *campaign_editor;
GtkWidget *mission_dialog;
